### ISSUE TITLE
Put python-dotenv in the packages section of the Pipfile instead of the dev-packages section

### ISSUE THREAD

**Issue by liammulh** [ClinGen/stanford-affils#129]
On the prod server, we `pipenv sync`. This only installs the dependencies in the packages section. It ignores the dev-packages section because those are supposed to be only used for development, i.e. not needed in prod. To make sure we have python-dotenv in prod, it needs to be in the packages section.

**Comment by sanchegm** [comment]
It looks like python-dotenv already exists in the packages section (see screenshot), do we need the version value to be the exact same ("1.*" vs "==1.*")?

![Screenshot 2024-10-16 at 10 46 44 AM](https://github.com/user-attachments/assets/90941b3f-a005-42c7-b552-34cb3e4e120a)

**Comment by liammulh** [comment]
Lol, I must have seen it in the dev-packages section and assumed it wasn't in the packages section. I believe it's redundant to have it in the packages and dev-packages section because `pipenv sync --dev` installs both sections. From the [docs](https://pipenv.pypa.io/en/stable/commands.html):

> `--dev — Install both develop and default package categories from Pipfile.`

**Comment by liammulh** [comment]
So I think it can be removed from the dev-packages section.
