### ISSUE TITLE
Ideate on new ID system

### ISSUE THREAD

**Issue by liammulh** [ClinGen/stanford-affils#73]
## Idea 1: Human-Readable Prefixes

Each affiliation gets an ID with a human-readable prefix. For example, there could be a GCEP with the ID `gcep_123`. Another example would be a VCEP with the ID `vcep_456`. The part after the underscore could be an integer or it could be an alpha-numeric string (along the lines of a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)). My preference would be an integer because it's easier to type in than an alpha-numeric string, and I don't think we need to worry about [enumeration attacks](https://www.upguard.com/blog/what-is-an-enumeration-attack) for the affiliations information.

**Comment by sanchegm** [comment]
On 07/24 meeting, Matt and Liam decided to keep the existing system based on external meeting held where 10000 number ID is used by other teams.
